# NumPy
NumPy, short for Numerical Python, is a powerful library in Python used for numerical computations. It provides support for arrays, matrices, and many mathematical functions. Let's dive into the basics and build up to more advanced concepts with examples and analogies.

## Understanding Arrays: The Building Blocks

At the core of NumPy is the array, which is similar to a list in Python but with added functionality and reduced versitality. Think of a NumPy array as a high-performance container for large datasets.

Before you start: [List vs Array: When to use](https://stackoverflow.com/a/176589)

## Creating Arrays

### 1D Array

In [1]:
[1,2,3,4]

[1, 2, 3, 4]

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


### 2D Array

In [4]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [5]:
type(arr_2d)

numpy.ndarray

## Array Properties

### Shape

In [6]:
arr.shape

(4,)

In [7]:
arr_2d.shape

(2, 3)

In [9]:
sh = (arr_2d.shape)
print(sh[0]) # rows
print(sh[1]) # columns

2
3


### Size

In [10]:
print(arr_2d.size)

6


### Data Type

In [ ]:
print(arr.dtype)

int64


In [ ]:
np.array([1, 2, 3, 4.0]).dtype

dtype('float64')

In [ ]:
np.array([1, 2, 3, 4.0, 'a']).dtype

dtype('<U32')

## Operations on Arrays

### Reshaping Arrays

In [ ]:
arr = np.arange(8)
print(arr)
print(arr.shape) # (8,)
reshaped_arr = arr.reshape((2, 2, 2))
print(reshaped_arr)
print(reshaped_arr.shape)

# convert any array into 1D (also called flattening of array)
print(reshaped_arr.reshape(-1)) # very, very common thing a data scientist will do

[0 1 2 3 4 5 6 7]
(8,)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
(2, 2, 2)
[0 1 2 3 4 5 6 7]


### Element-wise Addition

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [ ]:
# Scalar Addition
print(arr1 + 20) # np.array([1,2,3]) + np.array([20,20,20])
# Scalar Multiplication
print(arr1 * 20) # np.array([1,2,3]) * np.array([20,20,20])
# Scalar Subtraction
print(arr1 - 20)
# Scalar Division
print(arr1 / 20)

[21 22 23]
[20 40 60]
[-19 -18 -17]
[0.05 0.1  0.15]


### Element-wise Multiplication

In [ ]:
result = arr1 * arr2
print(result)

[ 4 10 18]


In [ ]:
# Element-wise Division
result = arr1 / arr2
print(result)

[0.25 0.4  0.5 ]


In [ ]:
# Element-wise Addition
result = arr1 + arr2
print(result)

[5 7 9]


In [ ]:
# Element-wise Subtraction
result = arr1 - arr2
print(result)

[-3 -3 -3]


In [ ]:
['a'] * 2

['a', 'a']

In [ ]:
np.array(['a']) * 2

TypeError: The 'out' kwarg is necessary. Use numpy.strings.multiply without it.

### Concatenation

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1.shape, arr2.shape)
concatenated = np.concatenate((arr1, arr2), axis=0) # concatenate a row
print(concatenated)

(2, 2) (2, 2)
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 8], [6, 9]]) # notice the change in arr2 shape
print(arr1.shape, arr2.shape)
concatenated = np.concatenate((arr1, arr2), axis=1) # concatenate a column
print(concatenated)

(2, 2) (2, 2)
[[1 2 5 8]
 [3 4 6 9]]


## Indexing and Slicing

### Indexing

https://stackoverflow.com/a/16096968

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(arr_2d[0, 1])

2


### Boolean Indexing

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
# Create a boolean array where the condition is true
condition = arr > 3
# np.array([1, 2, 3, 4, 5]) > np.array([3, 3, 3, 3, 3])
print(condition)
print(type(condition))


# Use this boolean array to filter the original array
filtered_arr = arr[condition]
print(filtered_arr)

[False False False  True  True]
<class 'numpy.ndarray'>
[4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[arr > 3]

array([4, 5])

### Fancy Indexing


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
fancy_indexed_arr = arr[indices]
print(fancy_indexed_arr)

[10 30 50]


### Slicing

In [ ]:
arr =np.concatenate([np.arange(0,6), np.arange(10,16), np.arange(20,26), np.arange(30,36), np.arange(40,46), np.arange(50,56)], axis = 0)
arr = arr.reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
arr[0,0:2]

array([0, 1])

In [ ]:
arr[0, 3:5]

array([3, 4])

In [ ]:
# notice the two square brackets in the output
arr[0:1, 3:5]

array([[3, 4]])

In [ ]:
arr[4:,4:]

array([[44, 45],
       [54, 55]])

In [ ]:
arr[:, 2:3]

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52]])

In [ ]:
arr[1:4, 2]

array([12, 22, 32])

In [ ]:
arr[1:4,2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [ ]:
arr[2, :]

array([20, 21, 22, 23, 24, 25])

In [ ]:
arr[:, :3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [ ]:
arr[:, 3:]

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25],
       [33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

In [ ]:
arr[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
arr[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

## Broadcasting

Broadcasting is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes.

### Broadcasting Example

In [ ]:
arr = np.array([1, 2, 3]) # np.array([[1,2,3], [1,2,3]])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
result = arr + arr2d # [[1+1, 2+2, 3+3], [1+4, 2+5, 3+6]]
print(result)

[[2 4 6]
 [5 7 9]]


In this example, the 1D array arr is "broadcast" across each row of the 2D array arr2d.

## Universal Functions

NumPy provides a range of functions that operate on arrays in an element-wise manner.



### Square Root

In [ ]:
arr = np.array([1, 4, 9, 16])
result = np.sqrt(arr)
print(result)

[1. 2. 3. 4.]


### Exponent

In [ ]:
result = np.exp(arr)
print(result)

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


## Aggregate Functions

### Mean

In [ ]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
print(mean)

3.0


### Standard Deviation

In [ ]:
std_dev = np.std(data)
print(std_dev)

1.4142135623730951


## Matrix Multiplication & Random Number Generation

### Matrix Multiplication

In [ ]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
result = np.dot(mat1, mat2)
print(result)

[[19 22]
 [43 50]]


### Random Number Generation

[PRNG](https://en.wikipedia.org/wiki/Pseudorandom_number_generator)

#### Random Array

In [ ]:
np.random.seed(42) # seed

rand_arr = np.random.rand(3, 2)
print(rand_arr)

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]


#### Normal Distribution

In [ ]:
normal_arr = np.random.randn(3, 2)
print(normal_arr)

[[ 1.57921282  0.76743473]
 [-0.46947439  0.54256004]
 [-0.46341769 -0.46572975]]
