In [1]:
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd
pd.set_option('display.max_rows', None)

In [3]:
help(fetch_openml)

Help on function fetch_openml in module sklearn.datasets._openml:

fetch_openml(name: Optional[str] = None, *, version: Union[str, int] = 'active', data_id: Optional[int] = None, data_home: Union[str, os.PathLike, NoneType] = None, target_column: Union[str, List, NoneType] = 'default-target', cache: bool = True, return_X_y: bool = False, as_frame: Union[str, bool] = 'auto', n_retries: int = 3, delay: float = 1.0, parser: str = 'auto', read_csv_kwargs: Optional[Dict] = None)
    Fetch dataset from openml by name or dataset id.

    Datasets are uniquely identified by either an integer ID or by a
    combination of name and version (i.e. there might be multiple
    versions of the 'iris' dataset). Please give either name or data_id
    (not both). In case a name is given, a version can also be
    provided.

    Read more in the :ref:`User Guide <openml>`.

    .. versionadded:: 0.20

    .. note:: EXPERIMENTAL

        The API is experimental (particularly the return value structure),
 

In [4]:
mnist = fetch_openml('mnist_784', version=1)

In [5]:
mnist_images = mnist.data.astype('float32')/255.0

In [6]:
mnist_images.max()

,0
pixel1,0.000000
pixel2,0.000000
pixel3,0.000000
pixel4,0.000000
pixel5,0.000000
pixel6,0.000000
pixel7,0.000000
pixel8,0.000000
pixel9,0.000000
pixel10,0.000000


In [7]:
mnist.DESCR

"**Author**: Yann LeCun, Corinna Cortes, Christopher J.C. Burges  \n**Source**: [MNIST Website](http://yann.lecun.com/exdb/mnist/) - Date unknown  \n**Please cite**:  \n\nThe MNIST database of handwritten digits with 784 features, raw data available at: http://yann.lecun.com/exdb/mnist/. It can be split in a training set of the first 60,000 examples, and a test set of 10,000 examples  \n\nIt is a subset of a larger set available from NIST. The digits have been size-normalized and centered in a fixed-size image. It is a good database for people who want to try learning techniques and pattern recognition methods on real-world data while spending minimal efforts on preprocessing and formatting. The original black and white (bilevel) images from NIST were size normalized to fit in a 20x20 pixel box while preserving their aspect ratio. The resulting images contain grey levels as a result of the anti-aliasing technique used by the normalization algorithm. the images were centered in a 28x28 

In [8]:
mnist.target.head()

,class
0,5
1,0
2,4
3,1
4,9


In [9]:
mnist.target_names

['class']

In [10]:
mnist.target.astype(int)[0:10]

,class
0,5
1,0
2,4
3,1
4,9
5,2
6,1
7,3
8,1
9,4


In [11]:
# One Hot Encoding using numpy eye
np.eye(10)[mnist.target.astype(int)[0:10]]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [12]:
help(pd.get_dummies)

Help on function get_dummies in module pandas.core.reshape.encoding:

get_dummies(data, prefix=None, prefix_sep: 'str | Iterable[str] | dict[str, str]' = '_', dummy_na: 'bool' = False, columns=None, sparse: 'bool' = False, drop_first: 'bool' = False, dtype: 'NpDtype | None' = None) -> 'DataFrame'
    Convert categorical variable into dummy/indicator variables.

    Each variable is converted in as many 0/1 variables as there are different
    values. Columns in the output are each named after a value; if the input is
    a DataFrame, the name of the original variable is prepended to the value.

    Parameters
    ----------
    data : array-like, Series, or DataFrame
        Data of which to get dummy indicators.
    prefix : str, list of str, or dict of str, default None
        String to append DataFrame column names.
        Pass a list with length equal to the number of columns
        when calling get_dummies on a DataFrame. Alternatively, `prefix`
        can be a dictionary mapp

In [13]:
mnist_lables = np.eye(10)[mnist.target.astype('int')]
mnist_lables[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [14]:
train_images, test_images, train_lables, test_lables = train_test_split(
    mnist_images, mnist_lables, test_size=0.2, random_state=42)

In [15]:
train_images.head()

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
47339,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12308,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32557,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
664,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [16]:
mnist_lables[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [30]:
# Activation Function
def relu(ws):
  return np.maximum(0, ws)

def softmax(ws):
  exp_ws = np.exp(ws - np.max(ws, axis=-1, keepdims=True))
  return exp_ws / np.sum(exp_ws, axis=-1, keepdims=True)

In [31]:
# Layer
def dense_layer_neurons(input, weights, bias, activation='relu'):
  weighted_sum = np.dot(input, weights) + bias
  return relu(weighted_sum) if activation == 'relu' else softmax(weighted_sum)

In [32]:
# Hyperparameters

imput_size = 28*28  # number of pixels in the image
hidden_size = 128   # Can be anything
output_size = 10    # number of classes

batch_size = 64
learning_rate = 0.1
epochs = 10
steps = len(train_images) // batch_size

In [33]:
# Initialize Weights
weights_input_hidden = np.random.randn(imput_size, hidden_size) * 0.01
bias_input_hidden = np.zeros((1, hidden_size))

weights_hidden_output = np.random.randn(hidden_size, output_size) * 0.01
bias_hidden_output = np.zeros((1, output_size))

weights_hidden_output = np.random.randn(hidden_size, output_size) * 0.01
bias_hidden_output = np.zeros((1, output_size))

In [34]:
weights_input_hidden

array([[ 0.00161053, -0.01562025,  0.00843656, ...,  0.000596  ,
         0.01156508,  0.01465768],
       [ 0.00469335, -0.00431951, -0.00308017, ...,  0.00313693,
        -0.00061329, -0.0007924 ],
       [-0.00624844,  0.00791314,  0.00169346, ...,  0.01168332,
        -0.01517422, -0.00094519],
       ...,
       [-0.0159406 , -0.01082431, -0.00677586, ..., -0.01207957,
        -0.01470284,  0.00257158],
       [ 0.01016727, -0.00766598,  0.00506439, ..., -0.01285717,
         0.00112467, -0.00686997],
       [ 0.00232507,  0.01536693,  0.01533508, ...,  0.00087187,
         0.00610735,  0.00115781]])

In [35]:
bias_input_hidden

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
weights_input_hidden.shape

(784, 128)

In [37]:
bias_input_hidden.shape

(1, 128)

In [38]:
# Total number of parameters
784*128 + 784 + 128*10 + 10

102426

In [41]:
# The Training Loop

for epoch in range(epochs):
  for step in range(steps):
    start_idx = step * batch_size
    end_idx = (step + 1) * batch_size

    # Forward Pass
    input_data = train_images[start_idx:end_idx]
    hidden_layer = dense_layer_neurons(input_data, weights_input_hidden, bias_input_hidden, activation='relu')
    output_layer = dense_layer_neurons(hidden_layer, weights_hidden_output, bias_hidden_output, activation='softmax')

    # Compute Loss - categorical crossentropy
    loss = -np.sum(train_lables[start_idx:end_idx] * np.log(output_layer + 1e-8)) / batch_size

    # Backward Pass (Gradient Descent)
    delta = output_layer - train_lables[start_idx:end_idx]
    gred_hidden = np.dot(delta, weights_hidden_output.T) * (hidden_layer > 0)  # Differenciation using matrix multiplication

    # Update weights and baises
    weights_hidden_output = weights_hidden_output - learning_rate * np.dot(hidden_layer.T, delta) / batch_size
    bias_hidden_output = bias_hidden_output - learning_rate * np.sum(delta, axis=0, keepdims=True) / batch_size

    weights_input_hidden = weights_input_hidden - learning_rate * np.dot(input_data.T, gred_hidden) / batch_size
    bias_input_hidden = bias_input_hidden - learning_rate * np.sum(gred_hidden, axis=0, keepdims=True) / batch_size

  # Compute Accuracy on validation set
  hidden_layer_val = dense_layer_neurons(test_images, weights_input_hidden, bias_input_hidden)
  output_layer_val = dense_layer_neurons(hidden_layer_val, weights_hidden_output, bias_hidden_output, activation='softmax')
  predictions = np.argmax(output_layer_val, axis=1)
  true_labels = np.argmax(test_lables, axis=1)
  accuracy = np.mean(predictions == np.argmax(test_lables, axis=1))

  print(f'Epoch {epoch + 1}/{epochs}, Loss: {loss:.4f}, Accuracy: {accuracy:.4f}')

Epoch 1/10, Loss: 0.0934, Accuracy: 0.9656
Epoch 2/10, Loss: 0.0885, Accuracy: 0.9679
Epoch 3/10, Loss: 0.0853, Accuracy: 0.9696
Epoch 4/10, Loss: 0.0795, Accuracy: 0.9703
Epoch 5/10, Loss: 0.0746, Accuracy: 0.9714
Epoch 6/10, Loss: 0.0724, Accuracy: 0.9719
Epoch 7/10, Loss: 0.0685, Accuracy: 0.9722
Epoch 8/10, Loss: 0.0645, Accuracy: 0.9729
Epoch 9/10, Loss: 0.0596, Accuracy: 0.9731
Epoch 10/10, Loss: 0.0546, Accuracy: 0.9729
